title: SCAMs@bristol
description: statistical chemical<br>analysis methods<br>@ the university of bristol
# logo: /assets/logo/logo.png
show_downloads: false
markdown: kramdown
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: team
    icon: fa-solid fa-people-group
    link: /team/
  - name: research
    icon: fa-solid fa-computer
    link: /research/
  - name: teaching
    icon: fa-solid fa-chalkboard-user
    link: /teaching/
  - name: news
    icon: fa-solid fa-newspaper
    link: /news/
  - name: publications
    icon: fa-solid fa-book
    link: /publications/
  - name: posters
    icon: fa-solid fa-image
    link: /posters/
  - name: code
    icon: fa-solid fa-code
    link: /code/
  - name: links
    icon: fa-solid fa-link
    link: /links/
  - name: contact
    icon: fa-solid fa-at
    link: /contact/

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

